// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGb8-q7vG2zYRkgsK912__vsvU9IejY_A',
    appId: '1:993385531866:web:3b3d96dbf3ebed46bc58e3',
    messagingSenderId: '993385531866',
    projectId: 'otuzbirapp',
    authDomain: 'otuzbirapp.firebaseapp.com',
    storageBucket: 'otuzbirapp.appspot.com',
    measurementId: 'G-LXSBNFSDL7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_ejjFIP4ckB5S1tAA3L3aP074Oth3XCw',
    appId: '1:993385531866:android:e7a4dbee9bf2ad43bc58e3',
    messagingSenderId: '993385531866',
    projectId: 'otuzbirapp',
    storageBucket: 'otuzbirapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC83FnkZkVyxC8wfUy1_xOQP1HnvO-y86s',
    appId: '1:993385531866:ios:ca8f82d67d2fc0dcbc58e3',
    messagingSenderId: '993385531866',
    projectId: 'otuzbirapp',
    storageBucket: 'otuzbirapp.appspot.com',
    iosBundleId: 'com.example.altmisdokuzapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC83FnkZkVyxC8wfUy1_xOQP1HnvO-y86s',
    appId: '1:993385531866:ios:ca8f82d67d2fc0dcbc58e3',
    messagingSenderId: '993385531866',
    projectId: 'otuzbirapp',
    storageBucket: 'otuzbirapp.appspot.com',
    iosBundleId: 'com.example.altmisdokuzapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGb8-q7vG2zYRkgsK912__vsvU9IejY_A',
    appId: '1:993385531866:web:92046f9f84b6138fbc58e3',
    messagingSenderId: '993385531866',
    projectId: 'otuzbirapp',
    authDomain: 'otuzbirapp.firebaseapp.com',
    storageBucket: 'otuzbirapp.appspot.com',
    measurementId: 'G-35EEGNZHKN',
  );
}
